# Generated by Django 4.0.5 on 2024-05-17 06:46

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100)),
                ('company_type', models.CharField(choices=[('IT', 'IT'), ('E-Commerce', 'E-Commerce'), ('BPO', 'BPO')], max_length=100)),
                ('added_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('employee_id', models.CharField(max_length=100)),
                ('phone_no', models.CharField(max_length=10)),
                ('address', models.CharField(max_length=150)),
                ('Working', models.BooleanField(default=True)),
                ('designation', models.CharField(choices=[('Intern', 'Intern'), ('Jr. developer', 'Jr. developer'), ('Senior developer', 'senior developer')], max_length=100)),
            ],
        ),
    ]
