# Generated by Django 4.0.5 on 2024-05-20 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0003_testimonial_delete_testimonials'),
    ]

    operations = [
        migrations.RenameField(
            model_name='testimonial',
            old_name='photos',
            new_name='picture',
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='rating',
            field=models.IntegerField(max_length=1),
        ),
    ]
